### PR TITLE
Merge develop into next

### PR DESCRIPTION
**Pull request by obycode**
### Applicable issues
- fixes #

### Checklist
- [ ] Test coverage for new or modified code paths
- [ ] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [ ] New integration test(s) added to `bitcoin-tests.yml`

### CODE REVIEW

**Comment by obycode** [comment]
Technically, I merged `chore/merge-master-to-develop` into `next`, because `chore/merge-master-to-develop` wasn't yet merged into `develop`.

**Comment by obycode** [comment]
I will go through and resolve the remaining errors before re-requesting reviews.

**Comment by obycode** [comment]
Ok, I think we should be ready for review now. Sorry about the false start earlier.

**Review by wileyj — APPROVED** [review]
shipit

**Review by kantai — APPROVED** [review]

**Comment by obycode** [comment]
@wileyj Thanks for the review. Did I mess anything up with the CI that is preventing the unit-tests from running?

**Comment by wileyj** [comment]
> @wileyj Thanks for the review. Did I mess anything up with the CI that is preventing the unit-tests from running?

not sure - i looked over the `.github` files being merged, they all looked correct. 
other jobs that are being checked also show up correctly: https://github.com/stacks-network/stacks-blockchain/actions/runs/6104536420/job/16566687096

i have a feeling this is a UI hiccup, because the unit-tests have indeed run successfully for this PR : https://github.com/stacks-network/stacks-blockchain/actions/runs/6104536420/job/16566687096

i would say it's a non-issue, but we can re-run the test to see if it's picked by the UI here.

**Comment by wileyj** [comment]
> @wileyj Thanks for the review. Did I mess anything up with the CI that is preventing the unit-tests from running?

all good - it was due to the naming of the test that caused the confusion. 
in the past, there was a workflow literally named "unit-tests" vs the one that was run here of "Unit Tests" via "CI/Release Tests". 

that older name was still a required step *for the next branch*. i've removed that requirement

**Pull request merged**
