### PR TITLE
updating metrics for issue 2987

### PR DESCRIPTION
**Pull request by wileyj**
2 metrics weren't as correct as they should be.
- `stacks_node_stacks_tip_height` was moved to the relayer. in tests, this proved to be a more effective location to track the data vs what `/v2/info` was reporting
- moved `stacks_node_neighbors_*` out of the pruning loop. this resulted in the metric being set more often, but the actual count of neighbors was far more accurate when compared to `/v2/neighbors`
- no changes were made to the mempool tx metric, to get this more accurate will be a far heavier lift. leaving for future work
- script used for testing: https://gist.github.com/wileyj/881eda423366134bc25e3fb5ec39ccbb

## Description
Some existing metrics were not as correct/up to date as they should be compared with `/v2` output.
  - `stacks_node_stacks_tip_height` was moved to the relayer. 
  - moved `stacks_node_neighbors_*` out of the pruning loop

In tests, the new locations of these directives showed much more accurate metric data when compared to the `/v2` output of a running/syncing stacks blockchain node. This change has no impact application developers and is not a breaking change. 
For details refer to issue https://github.com/stacks-network/stacks-blockchain/issues/2987

## Type of Change
- Bug fix

## Does this introduce a breaking change?
No

## Are documentation updates required?
No

## Testing information
No blockchain tests are necessary for this change. However, I used this script https://gist.github.com/wileyj/881eda423366134bc25e3fb5ec39ccbb to help determine the current state of accuracy, compared to the updates proposed in this PR. The changes proposed are much more closely aligned with what the blockchain reports via http over `/v2` endpoints.

### CODE REVIEW

**Review by jcnelson — APPROVED** [review]
LGTM, as long as it's getting you the data you need.

**Review by kantai — APPROVED** [review]
LGTM -- please add a changelog entry, though

**Comment by wileyj** [comment]
> LGTM -- please add a changelog entry, though

Added - let me know if it needs to be changed, wasn't entirely sure about the standard here for unreleased changes

**Comment by kantai** [comment]
> Added - let me know if it needs to be changed, wasn't entirely sure about the standard here for unreleased changes

Thanks -- because this PR is going to be included in 2.05.0.1.0, I think that entry should go under that section. I went ahead and moved it.

**Comment by wileyj** [comment]
> > Added - let me know if it needs to be changed, wasn't entirely sure about the standard here for unreleased changes
> 
> Thanks -- because this PR is going to be included in 2.05.0.1.0, I think that entry should go under that section. I went ahead and moved it.

Got it, thanks! wasn't sure if this PR would be included

**Pull request merged**
