### PR TITLE
2.05.0.2.0

### PR DESCRIPTION
**Pull request by jcnelson**
This is the first release candidate of the next stable Stacks blockchain node implementation.

- [X] The release must be timed so that it does not interfere with a prepare phase.

- [X] Before creating the release, the release manager must determine the version number for this release.

- [X] The release manager enumerates the PRs or issues that would block the release.

- [X] The release manager should open a develop -> master PR.

- [X] The release manager must update the CHANGELOG.md file with summaries what was Added, Changed, and Fixed.

- [X] Once the blocker PRs have merged, the release manager will create a new tag by manually triggering the stacks-blockchain Github Actions workflow against the develop branch, inputting the release candidate tag, 2.0.x.y.z-rc0, in the Action's input textbox.

- [x] Once the release candidate has been built, and docker images, etc. are available, the release manager will notify various ecosystem participants to test the release candidate on various staging infrastructure:

   - [X] Stacks Foundation staging environments.
   - [x] Hiro PBC testnet network.
   - [x] Hiro PBC mainnet mock miner.

- [X] The release candidate should be announced in the #stacks-core-devs channel in the Stacks Discord. For coordinating rollouts on specific infrastructure, the release manager should contact the above participants directly either through e-mail or Discord DM. The release manager should also confirm that the built release on the Github releases page is marked as Pre-Release.

- [X] The release manager will test that the release candidate successfully syncs with the current chain from genesis both in testnet and mainnet. This requires starting the release candidate with an empty chainstate and confirming that it synchronizes with the current chain tip.

- [X] Once the final release candidate has rolled out successfully without issue on the above staging infrastructure, the release manager tags 2 additional stacks-blockchain team members to review the develop -> master PR. If there is a merge conflict in this PR, this is the protocol: open a branch off of develop, merge master into that branch, and then open a PR from this side branch to develop. The merge conflicts will be resolved.

- [ ] Once reviewed and approved, the release manager merges the PR, and tags the release via the stacks-blockchain Github action by clicking "Run workflow" and providing the release version as the tag (e.g., 2.0.11.1.0) This creates a release and release images. Once the release has been created, the release manager should update the Github release text with the CHANGELOG.md "top-matter" for the release.

### CODE REVIEW

**Comment by kantai** [comment]
Can you add a release checklist to this PR's description, @jcnelson (https://github.com/stacks-network/stacks-blockchain/blob/master/README.md#non-consensus-breaking-release-process). It makes it much easier to follow the RC's process.

It may make things a bit easier in the future to add a PR template specifically for releases -- I'll open an issue about it.

**Comment by jcnelson** [comment]
Added

**Comment by gregorycoppola** [comment]
I love lists/check lists.

So, we'll approve once we hit the following:

> Once the final release candidate has rolled out successfully without issue on the above staging infrastructure, the release manager tags 2 additional stacks-blockchain team members to review the develop -> master PR. If there is a merge conflict in this PR, this is the protocol: open a branch off of develop, merge master into that branch, and then open a PR from this side branch to develop. The merge conflicts will be resolved.

**Comment by CharlieC3** [comment]
@jcnelson @kantai

When booting from a mock miner on mainnet with a pre-existing chainstate, we're seeing the miner crash soon after bootup with the following error:
```
{"msg":"Process abort due to thread panic: panicked at 'FAIL: problem instantiating cost tracking: CostComputationFailed(\"Unchecked(NoSuchDataVariable(\\\"confirmed-proposal-count\\\"))\")', src/clarity_vm/clarity.rs:281:18","level":"ERRO","ts":"2022-04-25T19:45:48.005122748+00:00","thread":"relayer","line":58,"file":"testnet/stacks-node/src/main.rs"}
{"msg":"Panic backtrace:    0: stacks_node::main::{{closure}}\n             at src/testnet/stacks-node/src/main.rs:59:18\n   1: std::panicking::rust_panic_with_hook\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18\n   4: rust_begin_unwind\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5\n   5: core::panicking::panic_fmt\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14\n   6: core::result::unwrap_failed\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5\n   7: core::result::Result<T,E>::expect\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1022:23\n      blockstack_lib::clarity_vm::clarity::ClarityInstance::begin_block\n             at src/src/clarity_vm/clarity.rs:275:17\n   8: blockstack_lib::chainstate::stacks::db::StacksChainState::inner_clarity_tx_begin\n             at src/src/chainstate/stacks/db/mod.rs:2043:32\n   9: blockstack_lib::chainstate::stacks::db::StacksChainState::chainstate_block_begin\n             at src/src/chainstate/stacks/db/mod.rs:1755:9\n      blockstack_lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::setup_block\n             at src/src/chainstate/stacks/db/blocks.rs:4904:30\n  10: blockstack_lib::chainstate::stacks::miner::<impl blockstack_lib::chainstate::stacks::StacksBlockBuilder>::epoch_begin\n             at src/src/chainstate/stacks/miner.rs:1721:13\n  11: blockstack_lib::chainstate::stacks::miner::<impl blockstack_lib::chainstate::stacks::StacksBlockBuilder>::build_anchored_block\n             at src/src/chainstate/stacks/miner.rs:1954:13\n  12: stacks_node::neon_node::StacksNode::relayer_run_tenure\n             at src/testnet/stacks-node/src/neon_node.rs:1944:44\n  13: stacks_node::neon_node::spawn_miner_relayer::{{closure}}\n             at src/testnet/stacks-node/src/neon_node.rs:1129:48\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:122:18\n  14: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:498:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40\n      std::panicking::try\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19\n      std::panic::catch_unwind\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:497:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5\n  15: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17\n  16: start_thread\n  17: clone\n","level":"ERRO","ts":"2022-04-25T19:45:48.075536243+00:00","thread":"relayer","line":60,"file":"testnet/stacks-node/src/main.rs"}
```

Booting a mock miner on mainnet from genesis does not hit this error. Nor does booting a standard follower on testnet from genesis, nor with a pre-existing chainstate.
Would it be worth converting our two testnet followers to mock miners to match our testing setup mainnet?

**Comment by kantai** [comment]
Hmm, this seems to be related to the block height calculation in the MARF. It seems like querying for the "0-height block" from the extended chain tip is returning the extended chain tip, even though the block height = 0 key returns the correct block hash from the parent:

These are log lines that I added to dig into what was happening:
```
INFO [1651155759.108323] [src/clarity_vm/clarity.rs:273] [chains-coordinator] begin_block, current: fafff8260b27168e6a3a984f3a1a15e0f303e81477364b114e0816030b69e38c, next: b40ffa12cd6cdec17a0cf0231bffb40d9271c319a5113e88792a3488765e6c6b, mainnet: true, epoch: 2.05
INFO [1651155759.110079] [src/chainstate/stacks/index/marf.rs:1227] [chains-coordinator] get_height_by_key, current_height: 1, queried_height: 0, current_block_hash: b40ffa12cd6cdec17a0cf0231bffb40d9271c319a5113e88792a3488765e6c6b, height_key: __MARF_BLOCK_HEIGHT_TO_HASH::0
INFO [1651155759.110130] [clarity/./src/vm/database/clarity_store.rs:118] [chains-coordinator] get_contract_hash, block_height: 0, block_hash: fafff8260b27168e6a3a984f3a1a15e0f303e81477364b114e0816030b69e38c
```

The "current" tip is `faff..`, the extending tip is `b40f..`, I added a log line to marf method for fetching block height -- already when it tries to get the "current" block height, you can see that something has gone wrong: `b40f..` thinks it is height 1, which is wrong. But once returned, the "0-height block" in that fork is returned as `faff..`, which is also wrong.

When I poll the MARF from `faff..` directly for the "0-height block", it returns the correct `55c9` (the genesis block):
```
$  ./target/debug/stacks-inspect marf-get /tmp/mock-miner/data/mainnet/chainstate/vm/index.sqlite fafff8260b27168e6a3a984f3a1a15e0f303e81477364b114e0816030b69e38c __MARF_BLOCK_HEIGHT_TO_HASH::0
55c9861be5cff984a20ce6d99d4aa65941412889bdc665094136429b84f8c2ee0000000000000000
```

I'll need to dig further to figure out how that node's MARF got into this state, it may have been something that happened while porting the databases.

**Comment by jcnelson** [comment]
> Looking into this issue now -- I've got the chainstate to reliably reproduce this error, so I should be able to figure out what's going on here.

What did you do to reproduce it?  Is this something from Hiro's infrastructure, or is there a general way to do it?

**Comment by kantai** [comment]
> Are there any other blocks where external_offset and external_length are 0?

Yes, ~33k:

```
$ sqlite3 /tmp/mock-miner/data/mainnet/chainstate/vm/clarity/marf.sqlite
SQLite version 3.37.0 2021-12-09 01:34:53
Enter ".help" for usage hints.
sqlite> SELECT COUNT(*) FROM marf_data WHERE external_offset = 0 AND external_length = 0;
32987
```

> Are there debug logs for the migration? Do you have a copy of the un-migrated old chainstate lying around somewhere that you can share?

I will poke around for debug logs from the migration, those I'm pretty sure I'll find.

Pre-migration chainstate will be harder.

**Comment by jcnelson** [comment]
> Yes, ~33k:

Yikes.  That's not ever supposed to happen.  Sounds like there's an error getting ignored somewhere.  I can update the code to add a sanity check as well.

**Comment by kantai** [comment]
Not much insight into _why_ the node stopped, but it does appear to have stopped during a migration:

```
Replaced block trie a0f92c20ad00452077861dbdee7acaf14863d6df4756886fa5f0866447bd1e4f at rowid 31337 offset 3346761640
```

Is the last log line before a 40 second gap, and then:

```
Loading config at path /src/stacks-node/Config.toml
stacks-node 2.05.0.2.0-rc2 (develop:118187d+, release build, linux [x86_64])
```

So a restart. Will poke around to see if I can figure out why the node exited (without the exit handler, because that would show up in the logs), but at least that tells us what went wrong in the db.

**Comment by kantai** [comment]
Hiro's mock miner and testnet nodes have upgraded to the release candidate, and reached the chain tip successfully

**Comment by jcnelson** [comment]
Got incremental vacuuming during the schema migration merged, as well as added a sanity check to verify that a migration was successful.

N.B. to anyone running a `-rc` candidate, you will need to update all of the MARF databases as follows so the new sanity check will work:

```
CREATE TABLE IF NOT EXISTS migrated_version (
    version INTEGER DEFAULT 1 NOT NULL
);
INSERT OR REPLACE INTO migrated_version (version) VALUES (2);
```

You'll need to do this for `mainnet/chainstate/vm/index.sqlite`, `mainnet/chainstate/vm/clarity/marf.sqlite` and `mainnet/burnchain/sortition/marf.sqlite`.

If you are running this code off of what's now in `develop` or from the (soon-to-be-released) 2.05.0.2.0 node from the current chainstate, then no action is needed.  This only affects people who were running `-rc` builds.

**Comment by jcnelson** [comment]
cc @kantai @pavitthrap @gregorycoppola

**Review by kantai — APPROVED** [review]

**Review by gregorycoppola — APPROVED** [review]
big release

thanks!

**Pull request merged**
