### PR TITLE
Feat/3596

### PR DESCRIPTION
**Pull request by jcnelson**
This PR addresses #3596 by enabling using a custom existing `bitcoind` wallet name when mining, instead of the default one ("") created by Stacks when it boots up for the first time.  This is pertinent for the `listunspent` and `importaddress` RPC calls that the node makes (h/t @MaksimalistT for bringing this up).

To use this feature, you will need to add 'wallet_name' to the '[burnchain]' section as follows:

```
[burnchain]
wallet_name = "name-of-your-wallet"
```

I have tested this with bitcoin 0.22.99.0.

### CODE REVIEW

**Review by obycode — APPROVED** [review]
lgtm

**Comment by kantai** [comment]
Untagging myself as a reviewer, because this seems like a great PR for newer reviewers!

**Comment by kantai** [comment]
Meta: What is the "L1 Working Group" tag supposed to be for? Does it mean "Everything that isn't sBTC"? In which case, I'd suggest that we just delete it as tag (because "Everything that isn't sBTC" is conveyed by the lack of an sBTC tag).

**Comment by igorsyl** [comment]
> Untagging myself as a reviewer, because this seems like a great PR for newer reviewers!

@jo-tm seize the opportunity!

**Comment by jcnelson** [comment]
> What is the "L1 Working Group" tag supposed to be for? Does it mean "Everything that isn't sBTC"? 

Right now, I've taken it to mean "things that improve the UX of the Stacks blockchain".  This includes both developer UX (i.e. refactoring) as well as performance and reliability improvements.  It does not include CI, devops, or docs.

**Comment by jo-tm** [comment]
@igorsyl sorting out my GH notifications. will review this today as a new contributor (next time in 48 hours as per the contributor guide)

**Review by pavitthrap — COMMENTED** [review]
lgtm

**Review by pavitthrap — APPROVED** [review]

**Review by jferrant — APPROVED** [review]

**Pull request merged**
