### PR TITLE
cherry-picking docker login env var commit

### PR DESCRIPTION
**Pull request by wileyj**
ref: https://github.com/stacks-network/stacks-blockchain/pull/3888

This is the develop branch with https://github.com/stacks-network/stacks-blockchain/pull/3888/commits/79d376057d4cea082ba2d24f20df7b84072ad079 cherry picked.

### CODE REVIEW

**Review by jbencin — APPROVED** [review]
Thanks! LGTM

**Review by kantai — APPROVED** [review]

**Comment by jbencin** [comment]
Well, I guess this didn't actually fix my specific issue. It was merged to `develop`, but the CI references `master`. So to actually get CI working on forks, we could...
- Merge this single commit into `master`
- Implement the `./.github/...` change

**Comment by jbencin** [comment]
We couldn't merge this branch to `master` as-is because that would introduce a lot of unwanted changes from `develop`. We'd have to cherry-pick this commit again onto the tip of `master` and make a new PR.

I will do that now

Also, I don't see any need to undo the change on `develop`. I don't think it matters one way or the other

**Comment by wileyj** [comment]
> We couldn't merge this branch to `master` as-is because that would introduce a lot of unwanted changes from `develop`. We'd have to cherry-pick this commit again onto the tip of `master` and make a new PR.
> 
> I will do that now
> 
> Also, I don't see any need to undo the change on `develop`. I don't think it matters one way or the other

true. only downside is it may create a conflict when develop is merged to master next

**Pull request merged**
