### PR TITLE
Fix: Parsing of config mixes connect_timeout and handshake_timeout

### PR DESCRIPTION
**Pull request by Acaccia**
### Description

A little mistake spotted randomly, where in the `connection_option` of the config file passed to stacks-node, `handshake_timeout` was replaced by `connect_timeout`.

### CODE REVIEW

**Review by igorsyl — APPROVED** [review]
Nice catch!

**Review by obycode — APPROVED** [review]
Yeah, good catch!

**Comment by Acaccia** [comment]
@obycode or @igorsyl 
Sorry, I forgot I created this PR :D
Could one of you please merge this branch, since you both approved it? I don't have the rights for it.

**Comment by obycode** [comment]
I just restarted the failing tests. Will merge once those pass.

**Pull request merged**
