### PR TITLE
Enable clippy in CI

### LINKED ISSUE #3979: [CI] Add clippy checks to the clarity subrepo
Depends on : https://github.com/stacks-network/stacks-blockchain/issues/3935

Add clippy checks for the clarity subrepo to CI. To run clippy on ONLY clarity, use `cargo clippy -p clarity --no-deps --tests --all-features`

### LINKED ISSUE #4020: [CI] Add clippy checks to pox-locking subrepo
Depends on : https://github.com/stacks-network/stacks-blockchain/issues/3937

Add clippy checks for the pox-locking subrepo to CI. To run clippy on ONLY pox-locking, use `cargo clippy -p pox-locking --no-deps --tests --all-features`

### LINKED ISSUE #4021: [CI] Add clippy checks to libstackerdb subrepo
Depends on : https://github.com/stacks-network/stacks-blockchain/issues/3936

Add clippy checks for the libstackerdb subrepo to CI. To run clippy on ONLY libstackerdb, use `cargo clippy -p libstackerdb --no-deps --tests --all-features`

### LINKED ISSUE #4022: [CI] Add clippy checks to stacks-common subrepo

### PR DESCRIPTION
**Pull request by obycode**
### Applicable issues
- fixes #3979
- fixes #4020 
- fixes #4021 
- fixes #4022
- see #3934

### Checklist
- [ ] Test coverage for new or modified code paths
- [ ] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [ ] New integration test(s) added to `bitcoin-tests.yml`

### CODE REVIEW

**Comment by obycode** [comment]
@wileyj after this is merged, can we add this "Clippy Check" as a required check?

**Comment by obycode** [comment]
Just realized that's probably not the right place to add the clippy job in ci.yml, since that one's only activated on pushes to master. I'm not clear on where it needs to go.

**Comment by obycode** [comment]
I reverted the changes to ci.yml, but I don't understand yet why this job doesn't actually run.

**Comment by obycode** [comment]
Ah, I'm an idiot:

```yml
    if: ${{ false }}
```

I'll try removing that.

**Review by wileyj — APPROVED** [review]
Approving this so we have something in place for now, with the expectation that we'll want to reimplement what this remote workflow does since it is no longer maintained:
https://github.com/actions-rs/clippy-check

**Pull request merged**
