### PR TITLE
Chore: Merge master to develop

### PR DESCRIPTION
**Pull request by kantai**
### Description

This merges the changes from master back into develop.

### CODE REVIEW

**Review by jcnelson — APPROVED** [review]

**Comment by kantai** [comment]
@wileyj -- it looks like the status checks for `develop` have to be updated to match the new CI action definitions that this is bringing in from `master`.

**Comment by wileyj** [comment]
thanks! develop matches master now

**Comment by kantai** [comment]
@wileyj -- it looks like "rustfmt" is still an expected check in `develop`.

**Comment by wileyj** [comment]
you are correct, my brain translated `rustfmt` to `Rust Format`. it's
adjusted now

**Pull request merged**
