### PR TITLE
chore: Merge `master` into `develop`

### PR DESCRIPTION
**Pull request by gregorycoppola**
### Description
`master` has had a lot of changes. Back-filling to `develop`.

### Checklist
- [x] Leverage existing tests
- [x] Brought up a miner from a historical snapshot

### CODE REVIEW

**Comment by gregorycoppola** [comment]
Running stacks-inspect over a snapshot that was previously working with a `master`-based branch leads to an error /cc @obycode who was talking about this as well:

```
temp-vm-001:~/stacks-blockchain$ sudo target/release/stacks-inspect try-mine /data/mainnet
thread 'main' panicked at 'Failed to open /data/mainnet/mainnet/burnchain/sortition: SqliteError(SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("no such table: snapshots")))', src/main.rs:728:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by gregorycoppola** [comment]
I can't run a mock miner on my old DB with this change.

```
sudo ../../target/release/stacks-node start --config conf/mainnet-mockminer-conf.toml 
[sudo] password for greg: 
INFO [1665149238.131009] [testnet/stacks-node/src/main.rs:82] [main] stacks-node 0.1.0 (merge/master-develop-oct2022:18e4b20a9, release build, linux [x86_64])
INFO [1665149238.131064] [testnet/stacks-node/src/main.rs:137] [main] Loading config at path conf/mainnet-mockminer-conf.toml
ERRO [1665149238.410056] [testnet/stacks-node/src/main.rs:58] [main] Process abort due to thread panic: panicked at 'FATAL: could not query sortition DB for maximum block height: SqliteError(SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("no such table: snapshots")))', src/chainstate/coordinator/mod.rs:899:14
```

**Comment by gregorycoppola** [comment]
Oh.. it's running on a different mock miner. maybe it was just somehow the chainstate.

**Comment by gregorycoppola** [comment]
i'll start a new mock miner from a hiro checkpoint

**Comment by gregorycoppola** [comment]
Oh, from a Hiro rolling snapshot, this branch caught up and mined blocks.

So, the manual "sync to chain tip" test is a pass.

**Review by obycode — APPROVED** [review]
This looks like a clean merge of master into develop. Thanks @gregorycoppola

**Review by jcnelson — APPROVED** [review]

**Pull request merged**
